import unittest

import asyncpg

PSQL_LIMIT = 65535
ACTIONS_DSN = "postgres://lightning:postgres_actions@localhost/postgres"


class TestArgLimit(unittest.TestCase):
    async def asyncSetUp(self):
        self.pool = await asyncpg.create_pool(dsn=ACTIONS_DSN)
        query = "CREATE TABLE arg_limit (idx BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, val INT);"
        await self.pool.execute(query)

    async def asyncTearDown(self):
        await self.pool.close()

    async def test_arg_limit(self):
        tmp = [i for i in range(PSQL_LIMIT)]
        async with self.pool.acquire() as con:
            await con.executemany("INSERT INTO arg_limit (val) VALUES ($1)", list(tmp))

        query = "SELECT COUNT(*) FROM arg_limit;"
        data = await self.pool.fetchval(query)
        self.assertEqual(data, PSQL_LIMIT)
