CREATE TABLE IF NOT EXISTS timers
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    expiry timestamp,
    created timestamp DEFAULT (now() at time zone 'utc'),
    event TEXT,
    extra JSONB
);

CREATE TABLE IF NOT EXISTS commands_usage
(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT,
    channel_id BIGINT,
    user_id BIGINT,
    used_at TIMESTAMP WITHOUT TIME ZONE,-- DEFAULT (now() at time zone 'utc'),
    command_name TEXT,
    failure BOOLEAN
);

CREATE INDEX IF NOT EXISTS commands_usage_guild_id_idx ON commands_usage (user_id, used_at, command_name);

CREATE TABLE IF NOT EXISTS nin_updates
(
    guild_id BIGINT PRIMARY KEY,
    id BIGINT,
    webhook_token VARCHAR (100)
);

CREATE TABLE IF NOT EXISTS guilds
(
    id BIGINT PRIMARY KEY,
    name TEXT NOT NULL,
    left_at timestamp without time zone,
    owner_id BIGINT NOT NULL,
    whitelisted BOOLEAN DEFAULT 't'
);

CREATE TABLE IF NOT EXISTS guild_config
(
    guild_id BIGINT PRIMARY KEY,
    prefixes TEXT [],
    autorole BIGINT,
    toggleroles BIGINT [],
    flags INT,
    "permissions" JSONB
);

CREATE TABLE IF NOT EXISTS guild_mod_config
(
    guild_id BIGINT PRIMARY KEY,
    warn_kick BIGINT,
    warn_ban BIGINT,
    mute_role_id BIGINT,
    temporary_mute_role_id BIGINT,
    raid_mode BOOLEAN DEFAULT 'f',
    flags INT
);

CREATE TABLE IF NOT EXISTS roles
(
    guild_id BIGINT,
    user_id BIGINT,
    roles BIGINT [],
    punishment_roles BIGINT [],
    UNIQUE (guild_id, user_id)
);

DO $$ BEGIN
    CREATE TYPE log_format_enum AS ENUM ('minimal with timestamp', 'minimal without timestamp', 'emoji', 'embed');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS logging
(
    guild_id BIGINT NOT NULL,
    channel_id BIGINT PRIMARY KEY,
    types INT,
    format log_format_enum DEFAULT 'minimal with timestamp',
    timezone TEXT
);

CREATE TABLE IF NOT EXISTS socket_stats
(
    event VARCHAR (100) PRIMARY KEY,
    count BIGINT DEFAULT '0'
);

CREATE TABLE IF NOT EXISTS command_bugs
(
    token VARCHAR (50) PRIMARY KEY,
    traceback TEXT,
    created_at timestamp without time zone
);

CREATE TABLE IF NOT EXISTS infractions
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id BIGINT,
    user_id BIGINT,
    moderator_id BIGINT,
    action INT,
    reason VARCHAR (2000),
    created_at timestamp without time zone DEFAULT (now() at time zone 'utc'),
    expiry timestamp without time zone,
    active BOOLEAN DEFAULT 't',
    extra JSONB
);

CREATE TABLE IF NOT EXISTS automod
(
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE PRIMARY KEY,
    config TEXT
);

-- I suppose this only supports one role menu
CREATE TABLE IF NOT EXISTS togglerole_interactions
(
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE PRIMARY KEY,
    channel_id BIGINT,
    message_id BIGINT
);