DO $$ BEGIN
    CREATE TYPE automod_event_type_enum AS ENUM ('message-content-spam', 'mass-mentions', 'message-spam', 'invite-spam', 'url-spam');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

DO $$ BEGIN
    CREATE TYPE automod_punishment_enum AS ENUM ('DELETE', 'WARN', 'MUTE', 'KICK', 'BAN');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

CREATE TABLE IF NOT EXISTS guild_automod_config
(
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE PRIMARY KEY,
    default_ignores BIGINT []
);

CREATE TABLE IF NOT EXISTS guild_automod_rules
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
    "type" automod_event_type_enum,
    "count" INT,
    seconds INT,
    ignores BIGINT []
);

CREATE TABLE IF NOT EXISTS guild_automod_punishment
(
    id BIGINT NOT NULL REFERENCES guild_automod_rules (id) ON DELETE CASCADE,
    "type" automod_punishment_enum,
    duration INT
);

DROP TABLE IF EXISTS automod;