CREATE TABLE IF NOT EXISTS message_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
    message_id BIGINT NOT NULL UNIQUE, -- The reported message id
    channel_id BIGINT NOT NULL,
    report_message_id BIGINT NOT NULL, -- The dashboard id
    dismissed BOOLEAN DEFAULT false,
    actioned BOOLEAN DEFAULT false
);

CREATE TABLE IF NOT EXISTS message_reporters (
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
    message_id BIGINT NOT NULL REFERENCES message_reports (message_id) ON DELETE CASCADE,
    author_id BIGINT NOT NULL,
    original BOOLEAN NOT NULL DEFAULT false,
    reason TEXT,
    reported_at TIMESTAMP WITHOUT TIME ZONE DEFAULT (now() at time zone 'UTC'),
    PRIMARY KEY ("message_id", "author_id")
);

ALTER TABLE guild_mod_config ADD COLUMN message_report_channel_id BIGINT;