-- Heat-based automod system
-- Stores configuration for heat thresholds and punishments

CREATE TABLE IF NOT EXISTS guild_automod_heat_config
(
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE PRIMARY KEY,
    enabled BOOLEAN DEFAULT 'f',
    decay_seconds INT DEFAULT 3600, -- How long it takes for heat to fully decay (1 hour default)
    heat_per_violation JSONB DEFAULT '{}'::jsonb -- Maps violation types to heat values
);

CREATE TABLE IF NOT EXISTS guild_automod_heat_thresholds
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY,
    guild_id BIGINT NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
    heat_threshold INT NOT NULL, -- Heat level that triggers this punishment
    punishment_type automod_punishment_enum NOT NULL,
    punishment_duration INT -- Duration in seconds for temporary punishments
);

CREATE INDEX IF NOT EXISTS guild_automod_heat_thresholds_guild_id_idx ON guild_automod_heat_thresholds(guild_id);
